fixtures:
  repositories:
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '3.2.0'
    nsswitch:
      repo: 'git://github.com/ghoneycutt/puppet-module-nsswitch.git'
      ref: 'v1.1.0'
    common:
      repo: 'git://github.com/ghoneycutt/puppet-module-common.git'
      ref: 'v1.0.2'
  symlinks:
    pam: "#{source_dir}"
